# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5bf8652bbc7421c841af8013ca14d3ea31d7288a2956cb1929938bd738fcf0df72936efc95f19a4ce8484aaa40f0fa67f67cf2a49ef21b407c516e6f8018e95

test:
  secret_key_base: 5a21e40a431191d2065d20c65d4e4fe65bc59ec9e0101a8407536527710d8353ae5407e719a9521a06d3d7bd49058bff603641d61cbf673b067b2bc926d3124c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
